[package]
name = "movecraft"
version = "0.0.1"


[addresses]
StarcoinFramework = "0x1"
StarcoinAssociation = "0xA550C18"
VMReserved = "0x0"
MoveCraft = "0xDEF"

[dev-dependencies]

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "cf1deda180af40a8b3e26c0c7b548c4c290cd7e7" }